CREATE TABLE origin_register (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    origin_id VARCHAR(50) NOT NULL,
    priority INT NOT NULL DEFAULT '2',
    threshold BIGINT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT index_priority_indicator_origin_id UNIQUE (origin_id)
);

ALTER TABLE golden_record_tasks ADD COLUMN origin_id VARCHAR(50) DEFAULT NULL;

CREATE INDEX index_origin_id ON golden_record_tasks (origin_id);

ALTER TABLE golden_record_tasks ADD COLUMN priority INT NOT NULL DEFAULT '2';
