apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bpdm-postgres.fullname" . }}
  labels:
    {{- include "bpdm-postgres.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "bpdm-postgres.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bpdm-postgres.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
                   {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: POSTGRES_DB
              value: bpdm
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.applicationSecrets  }}
                  key: db-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.applicationSecrets  }}
                  key: db-pass
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: {{ include "bpdm-postgres.fullname" . }}
              subPath: postgres
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: {{ include "bpdm-postgres.fullname" . }}
          persistentVolumeClaim:
            claimName: {{ include "bpdm-postgres.fullname" . }}
