{{/*
Copyright (c) 2021,2026 Contributors to the Eclipse Foundation

See the NOTICE file(s) distributed with this work for additional
information regarding copyright ownership.

This program and the accompanying materials are made available under the
terms of the Apache License, Version 2.0 which is available at
https://www.apache.org/licenses/LICENSE-2.0.

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
License for the specific language governing permissions and limitations
under the License.

SPDX-License-Identifier: Apache-2.0
*/}}

{{/*
Expand the name of the chart.
*/}}
{{- define "bpdm.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Create a default fully qualified app name.
We truncate at 63 chars because some Kubernetes name fields are limited to this (by the DNS naming spec).
If release name contains chart name it will be used as a full name.
*/}}
{{- define "bpdm.fullname" -}}
{{- if .Values.fullnameOverride -}}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- $name := default .Chart.Name .Values.nameOverride -}}
{{- if contains $name .Release.Name -}}
{{- .Release.Name | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}
{{- end -}}

{{/*
Names of the umbrella-managed wiring Secrets: the Postgres/Keycloak connection configs and the
Keycloak realm import. These are internal to the release - generated by the umbrella and consumed
only by its subcharts - so they derive purely from `.Release.Name`, the one identity visible in
every (sub)chart scope (a subchart's own nameOverride/fullnameOverride and `.Values` are not visible
across charts, but `.Release` is). That keeps producer and consumer in agreement without a shared
name override: the postgres/keycloak subcharts reference these same helpers from their `tpl`-rendered
values, so both sides compute (and truncate) the name identically. Use these for any name that must
match across the chart boundary.

Usage: include "bpdm.postgresConnectionConfig.name" .
*/}}
{{- define "bpdm.postgresConnectionConfig.name" -}}
{{- printf "%s-postgres-connection-config" .Release.Name | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{- define "bpdm.realmConfig.name" -}}
{{- printf "%s-realm" .Release.Name | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{- define "bpdm.gateKeycloakConfig.name" -}}
{{- printf "%s-gate-keycloak-config" .Release.Name | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{- define "bpdm.poolKeycloakConfig.name" -}}
{{- printf "%s-pool-keycloak-config" .Release.Name | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{- define "bpdm.cleaningDummyKeycloakConfig.name" -}}
{{- printf "%s-cleaning-dummy-keycloak-config" .Release.Name | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{- define "bpdm.orchestratorKeycloakConfig.name" -}}
{{- printf "%s-orchestrator-keycloak-config" .Release.Name | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{/*
Compute the base HTTP URL of the bundled Keycloak dependency.
Incorporates a non-80 httpPort when set; otherwise omits the port for a clean URL.

Usage: include "bpdm.keycloakUrl" .
*/}}
{{- define "bpdm.keycloakUrl" -}}
{{- $host := include "bpdm.dependencyFullname" (list . .Values.keycloak "keycloak") -}}
{{- $port := ((.Values.keycloak | default dict).service | default dict).httpPort | default 80 -}}
{{- if eq ($port | toString) "80" -}}
{{- printf "http://%s" $host -}}
{{- else -}}
{{- printf "http://%s:%v" $host $port -}}
{{- end -}}
{{- end -}}

{{/*
Create chart name and version as used by the chart label.
*/}}
{{- define "bpdm.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Common labels
*/}}
{{- define "bpdm.labels" -}}
helm.sh/chart: {{ include "bpdm.chart" . }}
{{ include "bpdm.selectorLabels" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}

{{/*
Selector labels
*/}}
{{- define "bpdm.selectorLabels" -}}
app.kubernetes.io/name: {{ include "bpdm.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

{{/*
Create name of application secret
*/}}
{{- define "bpdm.applicationSecret.name" -}}
{{- printf "%s-application" (include "bpdm.fullname" .) }}
{{- end }}

{{/*
Resolve the determined full name of a dependency (sub)chart from the umbrella context.
Delegates to "bpdm.fullname" by synthesizing the (sub)chart's own scope (.Chart/.Values/.Release),
so producer and consumer compute names through the exact same algorithm. Lets the umbrella compute
e.g. the deployed Postgres/Keycloak service name from the values it passes to those dependencies.

Usage: include "bpdm.dependencyFullname" (list $ $dependencyValues "chartName")
*/}}
{{- define "bpdm.dependencyFullname" -}}
{{- $ctx := index . 0 -}}
{{- $values := index . 1 | default dict -}}
{{- $chartName := index . 2 -}}
{{- include "bpdm.fullname" (dict "Release" $ctx.Release "Chart" (dict "Name" $chartName) "Values" $values) -}}
{{- end -}}

{{/*
Resolve the ordered list of externally provided application config Secret names.
Each `.Values.externalApplicationConfig` entry is a string holding the fully qualified name of an
existing Secret; it is rendered through `tpl` so it may reference helpers such as
`bpdm.postgresConnectionConfig.name`. Order is preserved and entries that render empty are dropped.
*/}}
{{/*
Resolve a secret value: use configuredValue if non-empty, otherwise look up key in an existing
Secret, otherwise generate a random 32-character alphanumeric string. Stable across upgrades as
long as the Secret persists in the cluster.

Usage: include "bpdm.resolveOrGenerateSecret" (list ctx secretName key configuredValue)
*/}}
{{- define "bpdm.resolveOrGenerateSecret" -}}
{{- $ctx := index . 0 -}}
{{- $secretName := index . 1 -}}
{{- $key := index . 2 -}}
{{- $configured := index . 3 | toString -}}
{{- if $configured -}}
{{- $configured -}}
{{- else -}}
{{-   $existing := lookup "v1" "Secret" $ctx.Release.Namespace $secretName -}}
{{-   if and $existing (hasKey ($existing.data | default dict) $key) -}}
{{-     index $existing.data $key | b64dec -}}
{{-   else -}}
{{-     randAlphaNum 32 -}}
{{-   end -}}
{{- end -}}
{{- end -}}

{{- define "bpdm.clientUrlConfig.name" -}}
{{- printf "%s-client-url-config" .Release.Name | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{/*
Compute the base HTTP URL of the bundled bpdm-orchestrator dependency.
Incorporates a non-80 service.port when set; otherwise omits the port for a clean URL.

Usage: include "bpdm.orchestratorUrl" .
*/}}
{{- define "bpdm.orchestratorUrl" -}}
{{- $values := index .Values "bpdm-orchestrator" | default dict -}}
{{- $host := include "bpdm.dependencyFullname" (list . $values "bpdm-orchestrator") -}}
{{- $port := ($values.service | default dict).port | default 80 -}}
{{- if eq ($port | toString) "80" -}}
{{- printf "http://%s" $host -}}
{{- else -}}
{{- printf "http://%s:%v" $host $port -}}
{{- end -}}
{{- end -}}

{{/*
Compute the base HTTP URL of the bundled bpdm-pool dependency.
Incorporates a non-80 service.port when set; otherwise omits the port for a clean URL.

Usage: include "bpdm.poolUrl" .
*/}}
{{- define "bpdm.poolUrl" -}}
{{- $values := index .Values "bpdm-pool" | default dict -}}
{{- $host := include "bpdm.dependencyFullname" (list . $values "bpdm-pool") -}}
{{- $port := ($values.service | default dict).port | default 80 -}}
{{- if eq ($port | toString) "80" -}}
{{- printf "http://%s" $host -}}
{{- else -}}
{{- printf "http://%s:%v" $host $port -}}
{{- end -}}
{{- end -}}

{{- define "bpdm.externalApplicationConfig.names" -}}
{{- $ctx := . -}}
{{- $names := list -}}
{{- range $ctx.Values.externalApplicationConfig | default list -}}
{{- $name := tpl . $ctx | trim -}}
{{- if $name -}}{{- $names = append $names $name -}}{{- end -}}
{{- end -}}
{{- $names | toJson -}}
{{- end -}}